import type { Metadata } from "next";
import { Montserrat, Dancing_Script, Cairo, Belleza } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header/header";
import { Footer } from "@/components/footer";

const montserrat = Montserrat({
  weight: ["400", "700"], 
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const dancingScript = Dancing_Script({
  weight: ["400", "700"], 
  variable: "--font-dancing-script",
  subsets: ["latin"],
});

const cairo = Cairo({
  weight: ["400"], 
  variable: "--font-cairo",
  subsets: ["latin"], 
});

const belleza = Belleza({
  weight: ["400"], 
  variable: "--font-belleza",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`antialiased flex flex-col min-h-screen ${montserrat.variable} ${dancingScript.variable} ${cairo.variable} ${belleza.variable}`}>
        
        <Header />

        <main className="flex-1 w-full">
          {children}
        </main>

        <Footer />

      </body>
    </html>
  );
}